apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: python-demo-app-grafana
  name: python-demo-app-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-demo-app-grafana
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: python-demo-app-grafana
    spec:
      containers:
      - args:
        - cfg:default.auth.anonymous.enabled=true
        - cfg:default.auth.anonymous.org_role=Admin
        - cfg:default.paths.provisioning=/provisioning
        image: grafana/grafana:5.3.0
        imagePullPolicy: Always
        name: python-demo-app-grafana
        env:
          - name: GF_PATHS_PROVISIONING
            value: "/provisioning"
        ports:
          - containerPort: 3000
            name: grafana
            protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /provisioning/datasources
            name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: grafanaconf
        name: config
---
apiVersion: v1
data:
  python-demo-app.yaml: |
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://python-demo-app-prometheus:9090
kind: ConfigMap
metadata:
  name: grafanaconf
---
apiVersion: v1
kind: Service
metadata:
  name: python-demo-app-grafana
spec:
  ports:
  - name: grafana
    port: 3000
    protocol: TCP
    targetPort: 9090
  selector:
    app: python-demo-app-grafana
  sessionAffinity: None
  type: ClusterIP
#
